yishengzhishui/js-wx

Gemfile
Gemfile.lock
app/controllers/products_controller.rb
app/views/common/_navbar.html.erb
app/views/products/search.html.erb
config/routes.rb

search function

---

app/assets/javascripts/account/products.coffee
app/assets/stylesheets/account/products.scss
app/controllers/account/products_controller.rb
app/controllers/products_controller.rb
app/helpers/account/products_helper.rb
app/models/product.rb
app/models/product_user_relationship.rb
app/models/user.rb
app/views/account/products/index.html.erb
app/views/common/_navbar.html.erb
app/views/products/show.html.erb
config/routes.rb
db/migrate/20170519130517_create_product_user_relationships.rb
db/schema.rb
test/controllers/account/products_controller_test.rb
test/fixtures/product_user_relationships.yml
test/models/product_user_relationship_test.rb

wx－collect

---

app/views/admin/products/index.html.erb

add delete btn in admin

---

app/assets/javascripts/admin/categories.coffee
app/assets/stylesheets/admin/categories.scss
app/controllers/admin/categories_controller.rb
app/controllers/admin/products_controller.rb
app/helpers/admin/categories_helper.rb
app/models/category.rb
app/models/product.rb
app/views/admin/categories/_form.html.erb
app/views/admin/categories/edit.html.erb
app/views/admin/categories/index.html.erb
app/views/admin/categories/new.html.erb
app/views/admin/products/_form.html.erb
app/views/admin/products/index.html.erb
app/views/layouts/admin.html.erb
config/routes.rb
db/migrate/20170521025300_create_categories.rb
db/migrate/20170521025329_add_category_to_product.rb
db/schema.rb
test/controllers/admin/categories_controller_test.rb
test/fixtures/categories.yml
test/models/category_test.rb

Wx new category

---

db/seeds.rb

category已经添加到seed档中了
现在直接git pull 拉到自己电脑上，运行rake db:seed 不会出现报错了

add category in seed

---

app/assets/javascripts/reviews.coffee
app/assets/stylesheets/reviews.scss
app/controllers/orders_controller.rb
app/controllers/reviews_controller.rb
app/helpers/reviews_helper.rb
app/models/product.rb
app/models/review.rb
app/models/user.rb
app/views/products/show.html.erb
app/views/reviews/_form.html.erb
app/views/reviews/_review.html.erb
config/routes.rb
db/migrate/20170523003151_create_reviews.rb
db/schema.rb
test/controllers/reviews_controller_test.rb
test/fixtures/reviews.yml
test/models/review_test.rb

implement review function

---

Gemfile
Gemfile.lock
app/controllers/products_controller.rb
app/models/product.rb
app/views/products/index.html.erb
app/views/products/show.html.erb
config/routes.rb
db/migrate/20170523005953_acts_as_votable_migration.rb
db/schema.rb

implement dianzan

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/views/welcome/index.html.erb
config/routes.rb

Wx landingpage

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/products.scss
app/views/products/index.html.erb
app/views/products/show.html.erb
app/views/reviews/_form.html.erb

主要修改了 products的show页面
对product的index页面做了部分修改

Wx product show

---

app/assets/javascripts/application.js
app/assets/stylesheets/products.scss
app/uploaders/image_uploader.rb
app/views/admin/products/edit.html.erb
app/views/products/index.html.erb
app/views/products/show.html.erb
db/seeds.rb

Wx product show image qiehuan

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/welcome.scss
app/views/common/_footer.html.erb
app/views/welcome/index.html.erb
config/initializers/carrierwave.rb

Reverts yishengzhishui/js-wx#15
将拆除  马静分支的那个 revert 再次revert

Revert "Revert "mj-landing_page_pictures&copy""

---

app/views/layouts/admin.html.erb
app/views/layouts/application.html.erb
db/seeds.rb

title的森生活 改为 幸福小站
seed档删掉生成商品的内容

debug and seed delete

---

app/views/admin/products/index.html.erb

在后台修改价格页面报错，在views/admin/products/index中第37行的product.category.name中加入了if product.category.
<%= product.category.name if product.category %>

add 'if product.category' to admin/products/index

---

app/assets/stylesheets/application.scss

alert margin

---

app/assets/stylesheets/products.scss
app/assets/stylesheets/welcome.scss
app/views/products/index.html.erb
app/views/products/show.html.erb

welcome and show image

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/products.scss
app/controllers/cart_items_controller.rb
app/controllers/products_controller.rb
app/models/cart.rb
app/views/carts/checkout.html.erb
app/views/carts/index.html.erb
app/views/order_mailer/apply_cancel.html.erb
app/views/order_mailer/notify_cancel.html.erb
app/views/order_mailer/notify_order_placed.html.erb
app/views/order_mailer/notify_ship.html.erb
app/views/orders/show.html.erb
app/views/products/show.html.erb
config/routes.rb
db/migrate/20170531025255_change_default_quantity_in_cart_item.rb
db/migrate/20170531083718_add_phonenumber_to_order.rb
db/schema.rb

修改了商品show页面的商品数量的改变以及同一商品较多数量直接加入购物车
购物车页面调整商品数量的按钮建立增加减少商品数量的功能
增加购买者以及收货人的电话
并在order－mailer中修改

Wx product quantity

---

app/assets/javascripts/application.js
app/assets/stylesheets/products.scss
app/controllers/products_controller.rb
app/views/account/products/index.html.erb
app/views/products/index.html.erb
app/views/products/show.html.erb
db/migrate/20170601032122_change_default_quantity_in_cart.rb
db/schema.rb

实作product/index页面的交互功能
将购物车以及点赞、收藏按钮布置上去。

product_index

---

Gemfile
Gemfile.lock
config/initializers/airbrake.rb

istall airbrake

---

app/views/carts/checkout.html.erb

debug address

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/welcome.scss
app/controllers/account/users_controller.rb
app/models/order.rb
app/views/account/users/edit.html.erb
app/views/carts/checkout.html.erb
app/views/order_mailer/apply_cancel.html.erb
app/views/order_mailer/notify_cancel.html.erb
app/views/order_mailer/notify_order_placed.html.erb
app/views/order_mailer/notify_ship.html.erb
app/views/welcome/index.html.erb
db/migrate/20170607070619_remove_billing_province.rb
db/migrate/20170607071513_address_details_to_user.rb
db/schema.rb

heroku 上的报错
user以及checkout 页面的用户地址的优化
背景图片高度的修改

Wx debug 6 7
